# Generated by Django 4.2.2 on 2023-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_detection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='predicted_probs',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
