# Generated by Django 4.2.2 on 2023-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detection_predicted_probs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='detection',
            name='predicted_probs',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
